
//------------------Switch time--------------------------------------------------
FC       1     TS1               001XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// RX---0
FC       100   TS1               001XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// RX---1
FC       100   TS1               001XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// RX---2
FC       100   TS1               001XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// RX---3
FC       1     TS1               001XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// RX---4
FC       10    TS1               011XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// BYPASS----trigger--5
FC       100   TS1              011XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// BYPASS---6
FC       1     TS1               011XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// BYPASS---7
FC       100   TS1               001XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// RX---8
FC       100   TS1               001XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// RX---9
FC       100   TS1               001XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// RX---10
FC       10    TS1               001XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// RX---11
FC       1     TS1               001XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// RX---12
FC       10    TS1               010XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// TX------trigger--13
FC       100   TS1               010XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// TX--14
FC       1     TS1               010XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// TX--15
FC       1     TS1               010XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// TX--16
FC       1     TS1               010XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// TX--17
FC       100   TS1               001XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// RX---trigger-----18
FC       100   TS1               001XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// RX--19
FC       100   TS1               001XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// RX--20
FC       1     TS1               001XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// RX--21
FC       10    TS1               010XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// TX---------------22
FC       100   TS1               010XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// TX--23
FC       1     TS1               010XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// TX--24
FC       100   TS1               000XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// OFF---trigger----25
FC       100   TS1               000XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// OFF--26
FC       100   TS1               000XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// OFF--27
FC       100   TS1               000XXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// OFF--28

//----------------
FC       1     TS1               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// reset--29
FC       1     TS1               XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;// reset--30






